export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const ADD_ONE_MENU_ITEM = 'ADD_ONE_MENU_ITEM';
export const REMOVE_ONE_MENU_ITEM = 'REMOVE_ONE_MENU_ITEM';
export const UPDATE_ORDERS = 'UPDATE_ORDERS';
export const DELETE_ORDER_FROM_ORDERS = 'DELETE_ORDER_FROM_ORDERS';
export const EDIT_ORDER = 'EDIT_ORDER';
export const NEW_ORDER = 'NEW_ORDER';